[workspace]
resolver = "2"
members = ["mcp"]
license = "MIT"

[workspace.lints.clippy]
all = "deny"
pedantic = "deny"
nursery = "deny"
manual_async_fn = { level = "allow", priority = 1 }
missing_panics_doc = { level = "allow", priority = 1 }
