name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    
    - name: Check formatting
      run: cargo fmt --all -- --check
      
    - name: Clippy
      run: cargo clippy -- -D warnings
      
    - name: Build
      run: cargo build --verbose --release
      
    - name: Run tests
      run: cargo test --verbose --release 
      
    - name: Install cargo-machete
      run: cargo install cargo-machete
      
    - name: Check for unused dependencies
      run: cargo machete